/* TinyQV bare-metal build configuration for the ported termcurses +
 * pdcurses (pdcurs34) + TUI stack.  Stands in for NuttX's autogenerated
 * config so the sources build with minimal diffs from the originals in
 * nuttx_riscv/apps.  This is the one place port configuration lives.
 */

#pragma once

/* Terminal stack: termcurses VT100 backend over the TinyQV UART, with
 * pdcurses input routed through termcurses (TERMINPUT).  The OSX alt
 * code table decodes the UTF-8 sequences Mac Terminal sends for
 * Alt-<key> (the TUI uses Alt-T and friends for tab switching).
 */

#define CONFIG_SYSTEM_TERMCURSES                    1
#define CONFIG_SYSTEM_TERMCURSES_VT100              1
#define CONFIG_SYSTEM_TERMCURSES_VT100_OSX_ALT_CODES 1
#define CONFIG_PDCURSES_TERMINPUT                   1
#define CONFIG_PDCURSES_HAVE_INPUT                  1

/* chtype is 32 bits: 16-bit char + attributes + color pair */

#define CONFIG_PDCURSES_CHTYPE_LONG                 1

/* No OS environment on bare metal (skips getenv paths) */

#define CONFIG_DISABLE_ENVIRON                      1

/* Deliberately OFF (framebuffer/NX rendering, input devices, threads,
 * wide chars): CONFIG_NX, CONFIG_PDCURSES_FBDEV, CONFIG_PDCURSES_WIDE,
 * CONFIG_PDCURSES_MULTITHREAD, CONFIG_PDCURSES_KEYBOARD,
 * CONFIG_PDCURSES_MOUSE, CONFIG_PDCURSES_DJOYSTICK,
 * CONFIG_PDCURSES_DEBUG, CONFIG_SYSTEM_TERMCURSES_DEBUG_KEYCODES
 */

/* NuttX decoration macros referenced throughout the sources */

#ifndef FAR
#  define FAR
#endif
#ifndef CODE
#  define CODE
#endif
#ifndef OK
#  define OK 0
#endif
#ifndef ERROR
#  define ERROR (-1)
#endif
#ifndef TRUE
#  define TRUE 1
#endif
#ifndef FALSE
#  define FALSE 0
#endif

/* C++ TUI sources: g++'s freestanding <stdlib.h> shadows newlib's and
 * omits the hosted heap/conversion prototypes, so declare the handful
 * the TUI uses.  <unistd.h> is not shadowed and supplies usleep/read/
 * write (with _GNU_SOURCE from the Makefile enabling strcasestr and
 * friends in <string.h>).
 */

#ifdef __cplusplus
#include <stddef.h>
#include <unistd.h>
extern "C" {
void *malloc(size_t size);
void *calloc(size_t nmemb, size_t size);
void *realloc(void *ptr, size_t size);
void free(void *ptr);
int atoi(const char *s);
long atol(const char *s);
}
#endif
